backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "posts"
    label: "פוסטים"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { label: "תוכן", name: "body", widget: "text" }
